plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Connor Macivor\\dev\\theticketwhisperer.com\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build --prod"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]